# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messenger.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='messenger.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0fmessenger.proto\"1\n\x04text\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x0c\n\x04recp\x18\x02 \x01(\t\x12\x0b\n\x03msg\x18\x03 \x01(\t2r\n\tmessenger\x12\x1b\n\x07\x63hatter\x12\x05.text\x1a\x05.text\"\x00\x30\x01\x12\x16\n\x04read\x12\x05.text\x1a\x05.text\"\x00\x12\x17\n\x05login\x12\x05.text\x1a\x05.text\"\x00\x12\x17\n\x03lru\x12\x05.text\x1a\x05.text\"\x00\x30\x01\x62\x06proto3')
)




_TEXT = _descriptor.Descriptor(
  name='text',
  full_name='text',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sender', full_name='text.sender', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='recp', full_name='text.recp', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg', full_name='text.msg', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=68,
)

DESCRIPTOR.message_types_by_name['text'] = _TEXT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

text = _reflection.GeneratedProtocolMessageType('text', (_message.Message,), dict(
  DESCRIPTOR = _TEXT,
  __module__ = 'messenger_pb2'
  # @@protoc_insertion_point(class_scope:text)
  ))
_sym_db.RegisterMessage(text)



_MESSENGER = _descriptor.ServiceDescriptor(
  name='messenger',
  full_name='messenger',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=70,
  serialized_end=184,
  methods=[
  _descriptor.MethodDescriptor(
    name='chatter',
    full_name='messenger.chatter',
    index=0,
    containing_service=None,
    input_type=_TEXT,
    output_type=_TEXT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='read',
    full_name='messenger.read',
    index=1,
    containing_service=None,
    input_type=_TEXT,
    output_type=_TEXT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='login',
    full_name='messenger.login',
    index=2,
    containing_service=None,
    input_type=_TEXT,
    output_type=_TEXT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='lru',
    full_name='messenger.lru',
    index=3,
    containing_service=None,
    input_type=_TEXT,
    output_type=_TEXT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MESSENGER)

DESCRIPTOR.services_by_name['messenger'] = _MESSENGER

# @@protoc_insertion_point(module_scope)
